[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/"
status = 200

[dev]
framework = "vite"
command = "npm run dev"
targetPort = 5173
functionsPort = 8888
autoLaunch = false

[build.environment]
NODE_VERSION = "18"
